name: Run jest tests

on:
    push:
        branches:
            - '**'
        paths-ignore:
            - 'README.md'
            - 'bin/**'

steps:
    - name: 'Populate auth file with SFDX_URL secret'
      shell: bash
      run: 'echo ${{ secrets.DEV_HUB_SFDXURL}} > ./SFDX_URL_STORE.txt'
    - name: 'Authenticate against dev hub'
      uses: forcedotcom/salesforcedx-actions@master
      with:
          args: 'force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=hub --setdefaultdevhubusername'
