name: 'Run jest tests'

on:
    push:
        branches:
            - '**'
        paths-ignore:
            - 'README.md'
            - 'bin/**'
jobs:
    sfdx_setup:
        name: 'SFDX devhub auth and test'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2
            - name: Install sfdx
              run: |
                  mkdir sfdx
                  wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
                  ./sfdx/install
                  echo ${{ secrets.DEV_HUB_SFDXURL }} > sfdx_auth
                  sfdx force:auth:sfdxurl:store -f sfdx_auth -d
            - uses: actions/checkout@v2
            - name: setup node ${{matrix.node-version}}
              uses: actions/setup-node@v1.4.1
              with:
                  node-version: ${{matrix.node-version}}
            - name: install packages
              run: yarn install
            - name: test
              run: yarn test
